controller_list:
  - name: phantomx_pincher_arm/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_shoulder_pan_joint
      - arm_bicep_joint
      - arm_forearm_joint
      - arm_wrist_flex_joint
      - gripper_link_joint
#  - name: phantomx_pincher_arm/gripper_controller
#    action_ns: gripper_cmd #gripper_action
#    type: GripperCommand
#    default: true
#    command_joint: gripper_joint
#    joints:
#      - gripper_joint
#Test for new 

  - name: phantomx_pincher_arm/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_joint
      - gripper2_joint
